### ISSUE TITLE
versionCode not increased

### ISSUE THREAD

**Issue by IzzySoft** [Septillion/Detect-Resolution#3]
Please remember increasing `versionCode` with each release (else Android doesn't consider new versions new). Currently, all releases show `versionCode: 1`.

Further: are there some screenshots? The description is a bit short to get a raw idea of the app's capabilities :wink:

**Comment by Septillion** [comment]
Thanks. 

Version code changes will be reflected in future updates. 

And you can find a screenshot on readme.md now.

**Comment by IzzySoft** [comment]
Thanks! Do you plan publishing on [F-Droid](https://f-droid.org/) and Google Play? If yes to one of those, may I recommend establishing [Fastlane file structure](https://gitlab.com/snippets/1895688)? That way you can maintain description, screenshot etc. in one central place – and use the very same structure for publishing to both catalogs (F-Droid would pick up Fastlane itself – and for Play you could use the Fastlane binaries to deploy). If you want, I can prepare an initial structure for you.

PS: by the way, what license do you use for your app?

**Comment by Septillion** [comment]
Thanks for suggesting! But this is a small personal project not meant for general availability. If it ever makes it to Google Play, I will make sure it have fancy packaging. 

:)

**Comment by Septillion** [comment]
Oh and I didn’t give much thought on licensing. So for now, just consider it as Creative Commons.

**Comment by IzzySoft** [comment]
Thanks, Frank! Just let me know if you want a simple "fastlane skeleton" zipped up, no big deal: I work with that stuff daily (disclosure: I'm one of the F-Droid maintainers). As for the license: CC is quite a spectrum (and usually not intended for code). So reading between the lines, you most likely think of something like [CC BY-SA](https://creativecommons.org/licenses/by-sa/4.0/) (short: you can copy, adapt, share under the same terms as long as you credit the original author)?

**Comment by Septillion** [comment]
I think I’m good here. Even if you generously provided the initial version, I doubt I’ll be patient enough to ever maintain it, lol. 

And about licensing... yes if you say so. But I don’t think I did enough for this project to be credited for anything. If anyone wants to use the code or anything they can just take it. 

Again, thanks for asking.

**Comment by IzzySoft** [comment]
Thanks! OK, then let's drop the fastlane idea (pick it up again whenever you feel like).

As for the license: IIRC the plain CC-SA had some issues. If you don't want to claim the BY, and wave all restrictions, an alternative would be [CC0](https://creativecommons.org/share-your-work/public-domain/cc0) (aka "[public domain](https://wiki.creativecommons.org/wiki/Public_domain)"). Just having "no license" leaves doubt (the default is often considered "all rights reserved" if not explicitly stated – and I take it that's not your intention).

**Comment by Septillion** [comment]
Thanks. This project is now marked as CC0.

**Comment by IzzySoft** [comment]
Great, thanks! Tonight's sync will update that [here](https://apt.izzysoft.de/fdroid/index/apk/com.frankseptillion.readresolution) (I hope you're OK with that listing :wink:)

Shall we close this issue then – or do we wait for the next release to confirm the topic is solved?

**Comment by IzzySoft** [comment]
*cough, cough* looks like it happened again: v1.0.9 has versionCode 3, as v1.0.8 already had.

**Comment by Septillion** [comment]
Thanks. Fixed.

**Comment by IzzySoft** [comment]
Thanks! My updater just picked it :smiley:
