### ISSUE TITLE
怎样理解 「Color Managed」?

### ISSUE THREAD

**Issue by devLiuGit** [Septillion/Detect-Resolution#4]

**Comment by devLiuGit** [comment]
看代码没有相关逻辑, 仅是图片中存在和页面背景颜色接近的文字.

**Comment by Septillion** [comment]
那张图片的色彩空间是 Rec 2020，若机器无法正确支持图片内置的 icc 配置文件，将会把它「挤压」到 sRGB，导致两侧的 NOT 可见（老型号的 Android 会有这个问题）。另外图片中 Color Managed 二词下半部分的颜色超出 sRGB 空间，若机器无法正确显示广色域内容，则看不出 Color Managed 的颜色分为两层。
